### ISSUE TITLE
1주차 정리

### ISSUE THREAD

**Issue by yummygyudon** [PinaryStudy/Git-Study#4]
### HEAD란?

Git 내의 연결하는 흐름 중에서 바라보고 있는 시점(머리)

---

#### Working Directory

- 변경 사항 발생
    - 파일 추가/삭제/수정
    - 파일 변경 (내용 추가/삭제)
    - 파일 경로 변경 등

`add` : 변경사항 기록 → ************************Snapshot 기록************************ → `Staging Area`

#### Staging Area

- 과거 기록 시점 직후 부터의 변경 사항들 중
`add` 된 변경 사항들이 저장되어 있는 영역
- `commit` 으로 묶게 되면 하나의 **변경 시점**으로서 기록

`commit` : 변경사항 저장 → `Local Repository`

#### Local Repository

- 기록된 `commit` 들의 영역

`push` : 변경사항 반영 & 업로드 → `Remote Repository`

---

### 깃의 4가지 상태

- `Untracked` :  Git이 추적하지 않는 상태
: *파일 자체를 **아예 처음 생성**해준 경우는 git이 변경사항을 추적하지 않는다.*
- Tracked : Git이 추적하는 상태
 : *파일 변경이 일어나면 Git이 알고 사용자에게 알려주는 상태*
    - `Unmodified` : Commit으로 저장 & 더 이상 변경이 없는 상태
    - `Modified` : Commit 한 저장 내용에서 추가적인 변경이 발생한 상태
    - `Staged` : Add 해서 Staging Area에 기록된 상태

---

### 자신만의 정리

역방향 관리
- `Remote Repository` → `Local Repository` : `pull`
- `Local Repository` → `Staging Area` : `reset --mixed`
- `Staging Area` → `Working Directory` : `restore --staged`

<br/>

```text
[Untracked]  [Unmodified]   [Modified]    [Staged]
    |              |             |            |
    |--------------------(add)--------------->|
    |              |<-----------(commit)------|
    |              |             |            |
    |              |--Edit file->|            |
    |              |             |--(add)---->|
    |<-Remove file-|             |            |
    |              |             |            |
```
⁜ _단, 위 Remove file이 Untracked 상태로 변환되는 것은 “**삭제되는 파일**”의 기준이지
전체 Flow 내에서는추적 중이던 <u>파일의 삭제 또한 변경으로 인식</u>하기 때문에 “삭제” 자체가 **변경으로서 기록**_

**작성자: 정동규** ( 32th YB Server )

**Comment by jinsu4755** [comment]
와우...플로우까지 정리 멋져요 :)
