### ISSUE TITLE
[최윤한] 1주차 정리

### ISSUE THREAD

**Issue by unanchoi** [PinaryStudy/Git-Study#7]
### HEAD란?

- HEAD는 현재 작업 중인 브랜치의 가장 최근 커밋을 가리키는 포인터.
- 현재 체크아웃된 커밋을 가리키는 포인터로서, 가장 최근의 커밋을 나타내며, 작업 디렉토리에서 수정 사항을 추가하거나, 새로운 커밋을 만들 때 기준이 된다.
-  보통 HEAD는 기본적으로 현재 브랜치의 가장 최근 커밋을 가리키지만, 다른 브랜치나 커밋을 체크아웃하면 HEAD가 가리키는 커밋이 변경됨.

### 깃의 3가지 영역

1. Working Directory :  add 되기 전, 작업하고 있는 파일들
3. Staging Area : add 된 상태. 
4. Repository : commit 된 상태.

### 깃의 4가지 상태

1. Untracked
- Working Directory에 있는 상태.
3. Modified
- 직전 커밋과 비교 했을 때 수정 된 상태
4. Unmodified
- 직전 커밋과 비교 했을 때 수정 되어 있지 않은 상태
5. Staged
- add된 상태

### 자신만의 정리

HEAD^
HEAD~4

**작성자: **
최윤한

**Comment by jinsu4755** [comment]
선생님 내용이 없어요... @unanchoi

**Comment by unanchoi** [comment]
@jinsu4755 채웠습니당
